import Foundation

/// Result generated by the formatter pipeline.
///
/// The formatter output separates the “raw” value used for storage/submission from the
/// “formatted” value displayed in the UI.
public struct FKTextFieldFormattingResult: Equatable, Sendable {
  /// Sanitized text without grouping separators.
  public let rawText: String
  /// Display text shown in UI.
  public let formattedText: String
  /// Indicates whether content was truncated by a max length constraint.
  public let isTruncated: Bool
  /// Indicates whether illegal characters were removed by filtering.
  public let removedIllegalCharacters: Bool

  /// Creates a formatting result.
  public init(
    rawText: String,
    formattedText: String,
    isTruncated: Bool,
    removedIllegalCharacters: Bool
  ) {
    self.rawText = rawText
    self.formattedText = formattedText
    self.isTruncated = isTruncated
    self.removedIllegalCharacters = removedIllegalCharacters
  }
}

/// Result generated by the validator pipeline.
///
/// Validators should return an actionable message for UI presentation when invalid.
public struct FKTextFieldValidationResult: Equatable, Sendable {
  /// Validation status.
  public let isValid: Bool
  /// Optional error message for invalid content.
  public let message: String?

  /// Creates a validation result.
  public init(isValid: Bool, message: String? = nil) {
    self.isValid = isValid
    self.message = message
  }

  /// Successful validation result.
  ///
  /// This is a computed property to keep Swift concurrency checks satisfied while
  /// maintaining a convenient “valid” sentinel value.
  public static var valid: FKTextFieldValidationResult {
    FKTextFieldValidationResult(isValid: true)
  }
}

