import Foundation

/// Context passed to action handlers so hosts can guard stale callbacks.
public struct FKRefreshActionContext: Sendable, Equatable {
  /// Monotonic token generated by the control when an action starts.
  public let token: UInt64
  /// Pull-to-refresh or load-more.
  public let kind: FKRefreshKind
  /// Trigger source used for analytics and policy decisions.
  public let source: FKRefreshTriggerSource
  /// Start timestamp from the configured clock.
  public let startedAt: Date

  public init(token: UInt64, kind: FKRefreshKind, source: FKRefreshTriggerSource, startedAt: Date) {
    self.token = token
    self.kind = kind
    self.source = source
    self.startedAt = startedAt
  }
}

